# Generated by Django 4.1 on 2022-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=1, upload_to='students/'),
            preserve_default=False,
        ),
    ]
